name: 'Gurgle&Whump'
favicon: null
layout_spectrum: 0.6959746954962611
typography_spectrum: 0.5084775602445006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.880835572257638
  lightness: 0.4841771984938532
  saturation: 0.9470776855014265
  rhythmicContrast: 0.7559071576688439
purpose: []
