name: Gurgle&Whump
favicon: null
layout_spectrum: 0.6959746954962611
typography_spectrum: 0.5084775602445006
title: Gurgle & Whump
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9ecc60'
    - '#fc4b99'
    - '#912b8d'
    - '#fe98c4'
  brandStrength: 0.880835572257638
  lightness: 0.4841771984938532
  saturation: 0.9470776855014265
  rhythmicContrast: 0.7559071576688439
purpose: []
